thoth-station/mi-scheduler

app.py
=> Expand logged messages lazily

app.py
=> Log workflow id to track actions

.github/CODEOWNERS, OWNERS
=> Assign Dominik to review PRs automatically

app.py
The method in thoth.common is again suffixed with '_workflow'
=> Rename to match method in thoth.common

app.py
See https://github.com/thoth-station/thoth-application/pull/145
=> get token from env variable

app.py
See more in https://github.com/thoth-station/common/pull/926
and in #30
=> Rename submit_srcopsmetrics_workflow to mi

app.py
This PR fixes #26 and requires https://github.com/thoth-station/common/pull/1037 
Remove utitilites that are now in openshift.
=> Remove and use utitilies that are now in openshift.

.thoth.yaml
Related-To: https://github.com/thoth-station/mi-scheduler/pull/54
=> update thoth yaml

app.py
Fixes https://github.com/thoth-station/mi-scheduler/issues/76
Kebechet analysis should be now stored in
`s3://thoth/data/{deployment-name}/thoth-sli-metrics/kebechet-update-manager/{repository-name}`
=> Add custom path for kebechet inspection

app.py
=> Use repo name correctly

.aicoe-ci.yaml, .prow.yaml
=> Add pytest and .prow.yaml

app.py
Related to https://github.com/thoth-station/common/pull/1141#issuecomment-805106406
=> Add additional_configuration parameter to kebechet

app.py
Related to https://github.com/thoth-station/common/pull/1141#discussion_r600814175
and https://github.com/thoth-station/mi/pull/348
=> Change additional_configuration to mi_thoth flag

app.py
Related to https://github.com/thoth-station/common/pull/1141#discussion_r601350991
=> Fix parameter name to be consistent with common

app.py
The kebechet analysis currently uses PRs and Issues
=> Make Kebechet entities inspection for PRs and Issues

app.py
Related to https://github.com/thoth-station/common/pull/1153
https://github.com/thoth-station/mi/pull/364
=> Add merge schedule, make arguments optional in Scheduler

.pre-commit-config.yaml, app.py
=> Change parameter merge to mi_merge

app.py
=> Add empty string as default value for subdir

app.py
Related to recent fix #162 
Seems like `click` has its own logic for specifying default values, therefore using it.
=> Change default value to be within click options

app.py
Related to https://github.com/thoth-station/thoth-application/pull/1809
=> Add mi entities extraction from envvar

app.py
Closes #188 
Reuse data from mi aggregation
/hold until changes to common are made
=> Change knowledge path to mi, add merge path for merge job

app.py
=> Add merge path argument for kebechet analyse workflows

app.py
Related to https://github.com/thoth-station/common/pull/1234
https://github.com/thoth-station/thoth-application/issues/1835
=> Add create_knowledge param for GH-related workflows

.pre-commit-config.yaml
Related to https://github.com/thoth-station/thoth-application/issues/2111#issuecomment-957617546
and https://github.com/thoth-station/mi-scheduler/pull/213#issuecomment-1069205890
=> Use https instead of git prefix

.pre-commit-config.yaml, Pipfile, Pipfile.lock, app.py
Related to #215 
Reason for this PR: did not want to wait for manual `Kebechet update` issue, which could in theory take a little longer time, the beer's on me this time!
=> Update thoth-common, add pre-commit to dev pckgs and pre-commit autoupdate 

.prow.yaml
Closes https://github.com/thoth-station/thoth-application/issues/2498
=> Update pre-commit prow image version to 0.14.3

.pre-commit-config.yaml
=> Enable mypy and black hooks in pre-commit config

app.py
Related to #249 
LOGGER printing for debugging means
=> Add debug information on kebechet repos

.prow.yaml
Committed via https://github.com/asottile/all-repos
=> update prow config
